### ISSUE TITLE
Can't really make it work with ESLint

### ISSUE THREAD

**Issue by valerioleo** [reviewdog/action-suggester#17]
First of all, thanks for the massive efforts around reviewdog. It's in plain sight the amount of work you poured in for everybody to enjoy.

I have been trying to set reviewdog in my CI on Github Actions and I only managed to see the reports, but never to get code suggestions. 

This is my current action file:

```
name: reviewdog
on: [pull_request]
jobs:
  eslint:
    runs-on: ubuntu-latest

    name: runner / eslint

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
          token: ${{ secrets.CI_ACCESS_TOKEN }}

      - uses: reviewdog/action-setup@v1
        with:
          reviewdog_version: latest

      - uses: reviewdog/action-eslint@v1
        env:
          REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          reporter: github-pr-review
          level: error
          filter_mode: added
      
      - uses: reviewdog/action-suggester@v1
        with:
          tool_name: eslint
```

Is there anything I'm missing?

In my understanding the `reviewdog/action-eslint@v1` action will output the result and the `reviewdog/action-suggester@v1` will print it as comments/suggestions. But really can't manage to make this work 🤷🏻‍♂️ 

Thank you so much for any help.

**Comment by airtonix** [comment]
It's pretty unclear how we're to use reviewdog effectively.

from my mere mortal peasant point of view, it looks like  : 

```
 - run: `eslint --fix` 
 - uses: reviewdog/action-suggester@v1
        with:
          tool_name: eslint
```

I say this because it says in the `README.md` : 

> ...which suggests any code changes based on diff ...
