### ISSUE TITLE
`/run/github-runner/runner1/_actions/reviewdog/action-setup/v1/install.sh: cannot execute: required file not found`

### ISSUE THREAD

**Issue by yvan-sraka** [reviewdog/action-suggester#35]
Hello,

I got an issue while working on https://github.com/input-output-hk/haskell.nix/pull/1983, you can see the logs [here](https://github.com/input-output-hk/haskell.nix/actions/runs/5658484232/job/15329898351?pr=1983):

```
Run reviewdog/action-suggester@v1
  with:
    tool_name: deadnix
    github_token: ***
    level: warning
    filter_mode: diff_context
    fail_on_error: false
    cleanup: true
  env:
    NIX_PATH: nixpkgs=channel:nixos-unstable
Run reviewdog/action-setup@v1
  with:
    reviewdog_version: v0.14.2
  env:
    NIX_PATH: nixpkgs=channel:nixos-unstable
Run $GITHUB_ACTION_PATH/install.sh
  $GITHUB_ACTION_PATH/install.sh
  shell: /nix/store/8fv91097mbh5049i9rglc73dx6kjg3qk-bash-5.2-p15/bin/bash --noprofile --norc -e -o pipefail {0}
  env:
    NIX_PATH: nixpkgs=channel:nixos-unstable
    REVIEWDOG_VERSION: v0.14.2
    REVIEWDOG_TEMPDIR: /run/github-runner/runner1/_temp
/run/github-runner/runner1/_temp/4afc4738-e60d-4450-b422-c30a1edec6b7.sh: line 1: /run/github-runner/runner1/_actions/reviewdog/action-setup/v1/install.sh: cannot execute: required file not found
Error: Process completed with exit code 127.
```

… which is surprising since my workflow code is pretty straightforward, where the issue could potentially come from?

```yaml
  deadnix:
    runs-on: [self-hosted, linux]
    steps:
      - uses: actions/checkout@v3
      - run: nix run github:astro/deadnix -- --edit --no-lambda-pattern-names
      - uses: reviewdog/action-suggester@v1
        with:
          tool_name: deadnix
```
